#include "std.h"
#include "interface.h"
#include "lpc_to_c.h"

static void LPC_wiz_beek_speedlpc__create() {
push_number(1);
push_number(3);
push_number(5);
push_number(4);
push_number(1);
C_AGGREGATE(2);
C_AGGREGATE(4);
C_LVALUE(&current_object->variables[variable_index_offset + 2]);
c_void_assign();
push_number(1);
C_STRING(3);
push_number(3);
C_STRING(4);
C_AGGREGATE_ASSOC(4);
C_LVALUE(&current_object->variables[variable_index_offset + 3]);
c_void_assign();
C_STRING(5);
C_LVALUE(&current_object->variables[variable_index_offset + 4]);
c_void_assign();
c_return_zero();
return;
}

static void LPC_wiz_beek_speedlpc__lfun0() {
c_return_zero();
return;
}

static void LPC_wiz_beek_speedlpc__lfun1() {
c_return_zero();
return;
}

static void LPC_wiz_beek_speedlpc__lfun2() {
c_return_zero();
return;
}

static void LPC_wiz_beek_speedlpc__lfun3() {
c_return_zero();
return;
}

static void LPC_wiz_beek_speedlpc__main() {
C_STRING(6);
c_void_assign_local(fp + 4);
C_STRING(7);
c_void_assign_local(fp + 5);
C_LOCAL(4);
C_LOCAL(5);
c_add();
c_void_assign_local(fp + 6);
push_number(5);
push_number(1);
push_number(3);
push_number(4);
push_number(2);
C_AGGREGATE(5);
c_void_assign_local(fp + 8);
push_number(9);
push_number(8);
push_number(7);
push_number(6);
push_number(10);
C_AGGREGATE(5);
c_void_assign_local(fp + 9);
push_number(4);
push_number(1);
C_AGGREGATE(2);
c_void_assign_local(fp + 10);
C_STRING(8);
C_STRING(9);
C_STRING(10);
C_STRING(11);
C_STRING(12);
C_STRING(13);
C_STRING(14);
C_STRING(15);
C_STRING(16);
C_STRING(17);
C_AGGREGATE_ASSOC(10);
c_void_assign_local(fp + 12);
C_STRING(18);
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label002;
label000:;label001:;C_LOOP_INCR(2);
label002:;C_LOOP_COND_NUM(2, 300); if (lpc_int)
goto label000;
label003:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 13);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label006;
label004:;label005:;C_LOOP_INCR(2);
label006:;C_LOOP_COND_NUM(2, 1000); if (lpc_int)
goto label004;
label007:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 14);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label010;
label008:;label009:;C_LOOP_INCR(2);
label010:;C_LOOP_COND_NUM(2, 10000); if (lpc_int)
goto label008;
label011:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 15);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label014;
label012:;label013:;C_LOOP_INCR(2);
label014:;C_LOOP_COND_NUM(2, 20000); if (lpc_int)
goto label012;
label015:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 16);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label018;
label016:;label017:;C_LOOP_INCR(2);
label018:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label016;
label019:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 17);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label022;
label020:;label021:;C_LOOP_INCR(2);
label022:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label020;
label023:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 18);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label026;
label024:;label025:;C_LOOP_INCR(2);
label026:;C_LOOP_COND_NUM(2, 200000); if (lpc_int)
goto label024;
label027:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 19);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label030;
label028:;label029:;C_LOOP_INCR(2);
label030:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label028;
label031:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 20);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label034;
label032:;C_LOCAL(21);
pop_stack();
label033:;C_LOOP_INCR(2);
label034:;C_LOOP_COND_NUM(2, 10000000); if (lpc_int)
goto label032;
label035:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label038;
label036:;C_LOCAL(21);
c_negate();
pop_stack();
label037:;C_LOOP_INCR(2);
label038:;C_LOOP_COND_NUM(2, 10000000); if (lpc_int)
goto label036;
label039:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(21);
C_GLOBAL(0);
C_LOCAL(21);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label042;
label040:;label041:;C_LOOP_INCR(2);
label042:;C_LOOP_COND_NUM(2, 3500000); if (lpc_int)
goto label040;
label043:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(23);
C_GLOBAL(0);
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(5000000);
c_void_assign_local(fp + 2);
f_rusage();
c_void_assign_local(fp + 0);
goto label046;
label044:;label045:;label046:;C_WHILE_DEC(2); if (lpc_int)
goto label044;
label047:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(24);
C_GLOBAL(0);
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(2500000);
c_void_assign_local(fp + 2);
f_rusage();
c_void_assign_local(fp + 0);
label048:;C_LVALUE(fp + 2);
c_post_dec();
C_BRANCH_WHEN_NON_ZERO(goto label049);
goto label051;
label049:;label050:;goto label048;
label051:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(25);
C_GLOBAL(0);
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label054;
label052:;C_LOCAL(4);
c_void_assign_local(fp + 3);
label053:;C_LOOP_INCR(2);
label054:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label052;
label055:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(26);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label058;
label056:;C_LOCAL(6);
c_void_assign_local(fp + 3);
label057:;C_LOOP_INCR(2);
label058:;C_LOOP_COND_NUM(2, 200000); if (lpc_int)
goto label056;
label059:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(27);
C_GLOBAL(0);
C_LOCAL(19);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label062;
label060:;C_LOCAL(4);
C_LOCAL(5);
c_add();
pop_stack();
label061:;C_LOOP_INCR(2);
label062:;C_LOOP_COND_NUM(2, 200000); if (lpc_int)
goto label060;
label063:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(28);
C_GLOBAL(0);
C_LOCAL(19);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label066;
label064:;C_LOCAL(4);
C_LOCAL(6);
c_add();
pop_stack();
label065:;C_LOOP_INCR(2);
label066:;C_LOOP_COND_NUM(2, 200000); if (lpc_int)
goto label064;
label067:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(29);
C_GLOBAL(0);
C_LOCAL(19);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label070;
label068:;C_LOCAL(6);
C_LOCAL(4);
c_add();
pop_stack();
label069:;C_LOOP_INCR(2);
label070:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label068;
label071:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(30);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label074;
label072:;C_LOCAL(6);
C_LOCAL(6);
c_add();
pop_stack();
label073:;C_LOOP_INCR(2);
label074:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label072;
label075:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(31);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label078;
label076:;C_LOCAL(4);
c_void_assign_local(fp + 3);
label077:;C_LOOP_INCR(2);
label078:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label076;
label079:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 22);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label082;
label080:;C_LOCAL(6);
c_void_assign_local(fp + 3);
label081:;C_LOOP_INCR(2);
label082:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label080;
label083:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 23);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label086;
label084:;C_LOCAL(4);
c_void_assign_local(fp + 3);
C_LOCAL(5);
C_LVALUE(fp + 3);
c_add_eq(1);
label085:;C_LOOP_INCR(2);
label086:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label084;
label087:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(32);
C_GLOBAL(0);
C_LOCAL(22);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label090;
label088:;C_LOCAL(4);
c_void_assign_local(fp + 3);
C_LOCAL(6);
C_LVALUE(fp + 3);
c_add_eq(1);
label089:;C_LOOP_INCR(2);
label090:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label088;
label091:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(33);
C_GLOBAL(0);
C_LOCAL(22);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label094;
label092:;C_LOCAL(6);
c_void_assign_local(fp + 3);
C_LOCAL(4);
C_LVALUE(fp + 3);
c_add_eq(1);
label093:;C_LOOP_INCR(2);
label094:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label092;
label095:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(34);
C_GLOBAL(0);
C_LOCAL(23);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label098;
label096:;C_LOCAL(6);
c_void_assign_local(fp + 3);
C_LOCAL(6);
C_LVALUE(fp + 3);
c_add_eq(1);
label097:;C_LOOP_INCR(2);
label098:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label096;
label099:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(35);
C_GLOBAL(0);
C_LOCAL(23);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label102;
label100:;push_number(100);
CHECK_TYPES(sp - 0, 2, 1, 173);
f_allocate();
c_void_assign_local(fp + 7);
label101:;C_LOOP_INCR(2);
label102:;C_LOOP_COND_NUM(2, 10000); if (lpc_int)
goto label100;
label103:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(36);
C_GLOBAL(0);
C_LOCAL(15);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label106;
label104:;push_number(1);
push_number(2);
push_number(3);
push_number(4);
push_number(5);
push_number(6);
push_number(7);
push_number(8);
push_number(9);
push_number(10);
C_AGGREGATE(10);
pop_stack();
label105:;C_LOOP_INCR(2);
label106:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label104;
label107:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(37);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label110;
label108:;C_STRING(8);
C_STRING(10);
C_STRING(12);
C_STRING(14);
C_STRING(16);
C_STRING(38);
C_STRING(39);
C_STRING(40);
C_STRING(41);
C_STRING(42);
C_AGGREGATE(10);
pop_stack();
label109:;C_LOOP_INCR(2);
label110:;C_LOOP_COND_NUM(2, 20000); if (lpc_int)
goto label108;
label111:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(43);
C_GLOBAL(0);
C_LOCAL(16);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label114;
label112:;C_LOCAL(8);
c_void_assign_local(fp + 7);
label113:;C_LOOP_INCR(2);
label114:;C_LOOP_COND_NUM(2, 200000); if (lpc_int)
goto label112;
label115:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(44);
C_GLOBAL(0);
C_LOCAL(19);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label118;
label116:;C_LOCAL(8);
C_LOCAL(9);
c_add();
pop_stack();
label117:;C_LOOP_INCR(2);
label118:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label116;
label119:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(45);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label122;
label120:;C_LOCAL(8);
C_LOCAL(10);
c_subtract();
pop_stack();
label121:;C_LOOP_INCR(2);
label122:;C_LOOP_COND_NUM(2, 20000); if (lpc_int)
goto label120;
label123:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(46);
C_GLOBAL(0);
C_LOCAL(16);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label126;
label124:;push_number(3);
C_LOCAL(8);
c_index();
pop_stack();
label125:;C_LOOP_INCR(2);
label126:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label124;
label127:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(47);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label130;
label128:;C_LOCAL(8);
c_void_assign_local(fp + 7);
label129:;C_LOOP_INCR(2);
label130:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label128;
label131:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label134;
label132:;C_LOCAL(8);
c_void_assign_local(fp + 7);
C_LOCAL(9);
C_LVALUE(fp + 7);
c_add_eq(1);
label133:;C_LOOP_INCR(2);
label134:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label132;
label135:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(48);
C_GLOBAL(0);
C_LOCAL(21);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label138;
label136:;C_LOCAL(8);
c_void_assign_local(fp + 7);
C_LOCAL(10);
C_LVALUE(fp + 7);
f_sub_eq();
pop_stack();
label137:;C_LOOP_INCR(2);
label138:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label136;
label139:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(49);
C_GLOBAL(0);
C_LOCAL(21);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label142;
label140:;push_number(100);
CHECK_TYPES(sp - 0, 2, 1, 151);
f_allocate_mapping();
c_void_assign_local(fp + 11);
label141:;C_LOOP_INCR(2);
label142:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label140;
label143:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(50);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label146;
label144:;push_number(1);
push_number(2);
push_number(3);
push_number(4);
push_number(5);
push_number(6);
push_number(7);
push_number(8);
C_AGGREGATE_ASSOC(8);
pop_stack();
label145:;C_LOOP_INCR(2);
label146:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label144;
label147:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(51);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label150;
label148:;C_STRING(8);
C_STRING(9);
C_STRING(10);
C_STRING(11);
C_STRING(12);
C_STRING(13);
C_STRING(14);
C_STRING(15);
C_STRING(16);
C_STRING(17);
C_AGGREGATE_ASSOC(10);
pop_stack();
label149:;C_LOOP_INCR(2);
label150:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label148;
label151:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(52);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label154;
label152:;C_STRING(12);
C_LOCAL(12);
c_index();
pop_stack();
label153:;C_LOOP_INCR(2);
label154:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label152;
label155:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(53);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label158;
label156:;C_STRING(38);
C_LOCAL(12);
c_index();
pop_stack();
label157:;C_LOOP_INCR(2);
label158:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label156;
label159:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(54);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label162;
label160:;C_LOCAL(12);
c_void_assign_local(fp + 11);
label161:;C_LOOP_INCR(2);
label162:;C_LOOP_COND_NUM(2, 200000); if (lpc_int)
goto label160;
label163:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(55);
C_GLOBAL(0);
C_LOCAL(19);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label166;
label164:;C_LOCAL(12);
c_void_assign_local(fp + 11);
label165:;C_LOOP_INCR(2);
label166:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label164;
label167:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label170;
label168:;C_LOCAL(12);
c_void_assign_local(fp + 11);
C_STRING(56);
C_STRING(38);
C_LVALUE(fp + 11);
push_indexed_lvalue(0);
c_void_assign();
label169:;C_LOOP_INCR(2);
label170:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label168;
label171:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(57);
C_GLOBAL(0);
C_LOCAL(21);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label174;
label172:;C_LOCAL(12);
c_void_assign_local(fp + 11);
push_number(0);
C_STRING(10);
C_LVALUE(fp + 11);
push_indexed_lvalue(0);
c_void_assign();
label173:;C_LOOP_INCR(2);
label174:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label172;
label175:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(58);
C_GLOBAL(0);
C_LOCAL(21);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label178;
label176:;C_LOCAL(12);
c_void_assign_local(fp + 11);
C_LOCAL(11);
C_STRING(10);
CHECK_TYPES(sp - 1, 32, 1, 152);
CHECK_TYPES(sp - 0, 1022, 2, 152);
f_map_delete();
label177:;C_LOOP_INCR(2);
label178:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label176;
label179:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(59);
C_GLOBAL(0);
C_LOCAL(21);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label182;
label180:;c_call(2, 0);
pop_stack();
label181:;C_LOOP_INCR(2);
label182:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label180;
label183:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(60);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label186;
label184:;push_number(1);
c_call(3, 1);
pop_stack();
label185:;C_LOOP_INCR(2);
label186:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label184;
label187:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(61);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label190;
label188:;C_STRING(3);
push_number(1);
c_call(4, 2);
pop_stack();
label189:;C_LOOP_INCR(2);
label190:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label188;
label191:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(62);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label194;
label192:;C_STRING(3);
push_number(1);
C_LOCAL(2);
c_call(5, 3);
pop_stack();
label193:;C_LOOP_INCR(2);
label194:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label192;
label195:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(63);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label198;
label196:;call_simul_efun(27, 0);
pop_stack();
label197:;C_LOOP_INCR(2);
label198:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label196;
label199:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(64);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label202;
label200:;f_this_object();
C_STRING(65);
CHECK_TYPES(sp - 1, 28, 1, 109);
CHECK_TYPES(sp - 0, 12, 2, 109);
st_num_arg = 2;
f_call_other();
pop_stack();
label201:;C_LOOP_INCR(2);
label202:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label200;
label203:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(66);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label206;
label204:;C_STRING(67);
C_STRING(65);
CHECK_TYPES(sp - 1, 28, 1, 109);
CHECK_TYPES(sp - 0, 12, 2, 109);
st_num_arg = 2;
f_call_other();
pop_stack();
label205:;C_LOOP_INCR(2);
label206:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label204;
label207:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(68);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label210;
label208:;f_this_object();
C_STRING(69);
CHECK_TYPES(sp - 1, 28, 1, 109);
CHECK_TYPES(sp - 0, 12, 2, 109);
st_num_arg = 2;
f_call_other();
pop_stack();
label209:;C_LOOP_INCR(2);
label210:;C_LOOP_COND_NUM(2, 50000); if (lpc_int)
goto label208;
label211:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(70);
C_GLOBAL(0);
C_LOCAL(17);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label214;
label212:;c_call(0, 0);
pop_stack();
label213:;C_LOOP_INCR(2);
label214:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label212;
label215:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(71);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label218;
label216:;c_call_inherited(0, 0, 0);
pop_stack();
label217:;C_LOOP_INCR(2);
label218:;C_LOOP_COND_NUM(2, 100000); if (lpc_int)
goto label216;
label219:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(72);
C_GLOBAL(0);
C_LOCAL(18);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label222;
label220:;C_STRING(73);
CHECK_TYPES(sp - 0, 4, 1, 136);
st_num_arg = 1;
f_save_object();
pop_stack();
label221:;C_LOOP_INCR(2);
label222:;C_LOOP_COND_NUM(2, 300); if (lpc_int)
goto label220;
label223:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(74);
C_GLOBAL(0);
C_LOCAL(13);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label226;
label224:;C_STRING(73);
CHECK_TYPES(sp - 0, 4, 1, 135);
st_num_arg = 1;
f_restore_object();
pop_stack();
label225:;C_LOOP_INCR(2);
label226:;C_LOOP_COND_NUM(2, 1000); if (lpc_int)
goto label224;
label227:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(75);
C_GLOBAL(0);
C_LOCAL(14);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label230;
label228:;push_number(0);
c_void_assign_local(fp + 21);
label229:;C_LOOP_INCR(2);
label230:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label228;
label231:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 22);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label234;
label232:;push_number(1);
c_void_assign_local(fp + 21);
label233:;C_LOOP_INCR(2);
label234:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label232;
label235:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 23);
push_number(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label239;
label236:;C_LOCAL(21);
C_BRANCH_WHEN_NON_ZERO(goto label237);
push_number(0);
c_void_assign_local(fp + 21);
label237:;label238:;C_LOOP_INCR(2);
label239:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label236;
label240:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(76);
C_GLOBAL(0);
C_LOCAL(22);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(1);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label244;
label241:;C_LOCAL(21);
C_BRANCH_WHEN_NON_ZERO(goto label242);
label242:;label243:;C_LOOP_INCR(2);
label244:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label241;
label245:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(77);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(1);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label249;
label246:;C_LOCAL(21);
C_BRANCH_WHEN_ZERO(goto label247);
push_number(1);
c_void_assign_local(fp + 21);
label247:;label248:;C_LOOP_INCR(2);
label249:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label246;
label250:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(78);
C_GLOBAL(0);
C_LOCAL(23);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label254;
label251:;C_LOCAL(21);
C_BRANCH_WHEN_ZERO(goto label252);
label252:;label253:;C_LOOP_INCR(2);
label254:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label251;
label255:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(79);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label259;
label256:;C_LOCAL(21);
push_number(1);
c_lt();
C_BRANCH_WHEN_ZERO(goto label257);
push_number(0);
c_void_assign_local(fp + 21);
label257:;label258:;C_LOOP_INCR(2);
label259:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label256;
label260:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(80);
C_GLOBAL(0);
C_LOCAL(22);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(1);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label264;
label261:;C_LOCAL(21);
push_number(1);
c_lt();
C_BRANCH_WHEN_ZERO(goto label262);
label262:;label263:;C_LOOP_INCR(2);
label264:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label261;
label265:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(81);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label269;
label266:;C_LOCAL(21);
C_BRANCH_WHEN_NON_ZERO(goto label267);
push_number(0);
c_void_assign_local(fp + 21);
label267:;label268:;C_LOOP_INCR(2);
label269:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label266;
label270:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(82);
C_GLOBAL(0);
C_LOCAL(22);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(1);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label274;
label271:;C_LOCAL(21);
C_BRANCH_WHEN_NON_ZERO(goto label272);
label272:;label273:;C_LOOP_INCR(2);
label274:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label271;
label275:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(83);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(1);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label279;
label276:;C_LOCAL(21);
push_number(1);
f_eq();
C_BRANCH_WHEN_ZERO(goto label277);
push_number(1);
c_void_assign_local(fp + 21);
label277:;label278:;C_LOOP_INCR(2);
label279:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label276;
label280:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(84);
C_GLOBAL(0);
C_LOCAL(23);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(0);
c_void_assign_local(fp + 21);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label284;
label281:;C_LOCAL(21);
push_number(1);
f_eq();
C_BRANCH_WHEN_ZERO(goto label282);
label282:;label283:;C_LOOP_INCR(2);
label284:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label281;
label285:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(85);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label288;
label286:;push_number(0);
c_void_assign_local(fp + 23);
label287:;C_LOOP_INCR(2);
label288:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label286;
label289:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_GLOBAL(0);
c_void_assign_local(fp + 21);
push_number(0);
c_void_assign_local(fp + 23);
push_number(1);
c_void_assign_local(fp + 22);
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label294;
label290:;C_LOCAL(23);
BRANCH_LINK( , goto label291);
C_LOCAL(23);
C_LAND(goto label291);
C_LOCAL(23);
label291:;C_BRANCH_WHEN_ZERO(goto label292);
push_number(0);
c_void_assign_local(fp + 23);
label292:;label293:;C_LOOP_INCR(2);
label294:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label290;
label295:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(86);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label300;
label296:;C_LOCAL(22);
BRANCH_LINK( , goto label297);
C_LOCAL(23);
C_LAND(goto label297);
C_LOCAL(23);
label297:;C_BRANCH_WHEN_ZERO(goto label298);
push_number(0);
c_void_assign_local(fp + 23);
label298:;label299:;C_LOOP_INCR(2);
label300:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label296;
label301:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(87);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label306;
label302:;C_LOCAL(22);
BRANCH_LINK( , goto label303);
C_LOCAL(22);
C_LAND(goto label303);
C_LOCAL(23);
label303:;C_BRANCH_WHEN_ZERO(goto label304);
push_number(0);
c_void_assign_local(fp + 23);
label304:;label305:;C_LOOP_INCR(2);
label306:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label302;
label307:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(88);
C_GLOBAL(0);
C_LOCAL(20);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
f_rusage();
c_void_assign_local(fp + 0);
push_number(0);
c_void_assign_local(fp + 2);
goto label312;
label308:;C_LOCAL(22);
BRANCH_LINK( , goto label309);
C_LOCAL(22);
C_LAND(goto label309);
C_LOCAL(22);
label309:;C_BRANCH_WHEN_ZERO(goto label310);
push_number(0);
c_void_assign_local(fp + 23);
label310:;label311:;C_LOOP_INCR(2);
label312:;C_LOOP_COND_NUM(2, 1000000); if (lpc_int)
goto label308;
label313:;f_rusage();
c_void_assign_local(fp + 1);
C_STRING(19);
C_LOCAL(1);
c_index();
C_STRING(20);
C_LOCAL(1);
c_index();
c_add();
C_STRING(19);
C_LOCAL(0);
c_index();
c_subtract();
C_STRING(20);
C_LOCAL(0);
c_index();
c_subtract();
C_LVALUE(&current_object->variables[variable_index_offset + 0]);
c_void_assign();
C_STRING(89);
C_GLOBAL(0);
C_LOCAL(21);
c_subtract();
c_add();
C_STRING(22);
c_add();
CHECK_TYPES(sp - 0, 1022, 1, 142);
f_write();
push_number(1);
c_return();
return;
}



static void (*functions[])() = {
LPC_wiz_beek_speedlpc__create,
LPC_wiz_beek_speedlpc__lfun0,
LPC_wiz_beek_speedlpc__lfun1,
LPC_wiz_beek_speedlpc__lfun2,
LPC_wiz_beek_speedlpc__lfun3,
LPC_wiz_beek_speedlpc__main,
0
};

interface_t LPCINFO_wiz_beek_speedlpc = {
    "wiz/beek/speedlpc",
    functions,
    0
};
