/* Do not remove the headers from this file! see /USAGE for more info. */

#ifndef __DAEMONS_H__
#define __DAEMONS_H__

#define ACCOUNT_D     "/daemons/account_d"
#define ALIAS_D       "/daemons/alias_d"
#define ANSI_D        "/daemons/ansi_d"
#define ANNOTATION_D  "/daemons/annotation_d"
#define ATTRIBUTES_D  "/daemons/attributes_d"
#define BANISH_D      "/daemons/banish_d"
#define BIRTHDAY_D    "/daemons/birthday_d"
#define BODY_D        "/daemons/body_d"
#define CHANLOG_D     "/daemons/chanlog_d"
#define CHANNEL_D     "/daemons/channel_d"
#define DID_D         "/daemons/did_d"
#define DOC_D 	      "/daemons/doc_d"
#define GROUP_D       "/daemons/group_d"
#define GUEST_D       "/daemons/guest_d"
#define GUILD_D       "/daemons/guild_d"
#define HELP_D        "/daemons/help_d"
#define IMUD_D        "/daemons/imud_d"
#define LAST_LOGIN_D  "/daemons/last_login_d"
#define MAILBOX_D     "/daemons/mailbox_d"
#define MESSAGES_D    "/daemons/messages_d"
#define METHOD_D      "/daemons/method_d"
#define MONEY_D       "/daemons/money_d"
#define NEWS_D        "/daemons/news_d"
#define PREPOSITION_D "/daemons/preposition_d"
#define QUEST_D       "/daemons/quest_d"
#define RACE_D        "/daemons/race_d"
#define REPORTER_D    "/daemons/reporter_d"
#define SHUTDOWN_D    "/daemons/shutdown_d"
#define SKILL_D       "/daemons/skill_d"
#define SOUL_D        "/daemons/soul_d"
#define SPELL_D       "/daemons/spell_d"
#define TASK_D        "/daemons/task_d"
#define TEAM_D        "/daemons/team_d"
#define TIMER_D       "/daemons/timer_d"
#define VERB_D        "/daemons/verb_d"
#define WEATHER_D     "/daemons/weather_d"

#define CMD_D         "/secure/daemons/cmd_d"
#define FINGER_D      "/secure/daemons/finger_d"
#define FTP_D         "/secure/daemons/ftp_d"
#define HTTP_D        "/secure/daemons/http_d"
#define IMAIL_D       "/secure/daemons/imail_d"
#define LOG_D         "/secure/daemons/log_d"
#define LPSCRIPT_D    "/secure/daemons/lpscript_d"
#define MAIL_D        "/secure/daemons/mail_d"
#define RCP_D         "/secure/daemons/rcp_d"
#define SECURE_D      "/secure/daemons/secure_d"
#define SMTP_D        "/secure/daemons/smtp_d"
#define SNOOP_D       "/secure/daemons/snoop_d"
#define USER_D        "/secure/daemons/user_d"

// ### obsolete
// Define these only if you want intermud services.
#define REMOTE_D        "/secure/daemons/remote"
#define CHANGW_D	"/daemons/changw"

#endif // __DAEMONS_H__
