#!/bin/bash
#	Bash script to keep the mud up forever
#	Rust July 7, 1994

# modify as necessary
limadir=/home/mud/lima-1.0a4

########################################
logdir=$limadir/lib/log
logs="driver.log catch runtime log"
logfile=$logdir/driver.log

bindir=$limadir/etc
driver=./driver
config=./config.lima

while true; do

cd $bindir

for f in $logs ; do mv -f $logdir/$f $logdir/$f.old > /dev/null 2>&1 ; done

date > $logfile
$driver $config >> $logfile 2>&1

done
