#!/bin/bash
#	Bash script to keep the mud up forever
#	Rust July 7, 1994

limadir=/home/mud/lima-0.9r10

logdir=$limadir/lib/log
logfile=$logdir/driver.log
lastlog=$logdir/driver.log.old

bindir=$limadir/etc
driver=./driver
config=./config.lima

while true; do

cd $bindir

mv -f $logfile $lastlog

date > $logfile
$driver $config >> $logfile 2>&1

done
