#!/bin/bash
#	Bash script to keep the mud up forever
#	Rust July 7, 1994

$LIMADIR=/home/rust/lima0.9-alpha

logdir=$LIMADIR/lib/log
logfile=$logdir/driver.log
lastlog=$logdir/driver.log.old

bindir=$LIMADIR/etc
driver=./driver
config=./config.quendor

while true; do

cd $bindir
rm -f $lastlog
mv $logfile $lastlog

date > $logfile
$driver $config >> $logfile 2>&1

done
