#define MAIN     "/domains/std/school/"
#define R        MAIN + "R/"
#define A        MAIN + "A/"
#define W        MAIN + "W/"
#define M        MAIN + "M/"
#define F        MAIN + "F/"
#define O        MAIN + "O/"
